### ISSUE TITLE
Building a window results in an "explicit panic" on Windows

### ISSUE THREAD

**Issue by LaylBongers** [PistonDevelopers/glutin_window#120]
This is happening both in my own code and when running the examples.

```
thread 'main' panicked at 'explicit panic', C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.3\src\platform\windows\window.rs:160
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<&str>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: winit::platform::platform::window::Window::platform_window
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.3\src\platform\windows\window.rs:160
   6: winit::Window::platform_window
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.3\src\window.rs:264
   7: glutin::platform::platform::context::Context::new
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\platform\windows\context.rs:51
   8: glutin::platform::platform::Context::new
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\platform\windows\mod.rs:69
   9: glutin::GlWindow::new
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\lib.rs:322
  10: glutin_window::GlutinWindow::new
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.38.0\src\lib.rs:102
  11: glutin_window::{{impl}}::build_from_window_settings
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.38.0\src\lib.rs:399
  12: window::WindowSettings::build<glutin_window::GlutinWindow>
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-window-0.27.0\src\lib.rs:387
  13: calcium_rendering_static::gfx_opengl::{{impl}}::window
             at C:\Users\Layl\Desktop\DamageReport\libraries\rendering\calcium-rendering-static\src\gfx_opengl.rs:38
  14: carpenter::runtime::{{impl}}::run<calcium_rendering_static::gfx_opengl::GfxOpenGlInitializer>
             at .\src\runtime.rs:25
  15: calcium_rendering_static::runtime::run_runtime<carpenter::runtime::StaticRuntime>
             at C:\Users\Layl\Desktop\DamageReport\libraries\rendering\calcium-rendering-static\src\runtime.rs:10
  16: carpenter::run_game
             at .\src\main.rs:52
  17: carpenter::main
             at .\src\main.rs:32
  18: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  19: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  20: main
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  22: BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\carpenter.exe` (exit code: 101)
```

**Comment by LaylBongers** [comment]
kvark discovered this problem is being caused by glutin calling `platform_window`, which is deprecated and panics

**Comment by LaylBongers** [comment]
This specific crash has been resolved
