### ISSUE TITLE
Crash creating window

### ISSUE THREAD

**Issue by simendsjo** [PistonDevelopers/glutin_window#45]
I'm trying to run the little game [rocket](https://github.com/aochagavia/rocket), but it crashes on start. Looks like the problem is creating the glutin window:

```
$ RUST_BACKTRACE=1 ./rocket                                                                                                         
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', src/libcore/result.rs:731
stack backtrace:
   1:     0x7f1d289d713e - sys::backtrace::write::h038220f50279f177vus
   2:     0x7f1d289da505 - panicking::on_panic::h71219c6695575a6bpgx
   3:     0x7f1d289d273e - rt::unwind::begin_unwind_inner::h82aba8beb356b6583Vw
   4:     0x7f1d289d2cfc - rt::unwind::begin_unwind_fmt::h39b470f67c9e92b29Uw
   5:     0x7f1d289d9ef6 - rust_begin_unwind
   6:     0x7f1d28a0cbc4 - panicking::panic_fmt::hc9237b7ecab48700neC
   7:     0x7f1d28811d21 - result::Result<T, E>::unwrap::h2411068402462984045
                        at src/libcore/macros.rs:28
   8:     0x7f1d2880cd8f - GlutinWindow::new::ha1e3edbd4f8b8ccaKaa
                        at /home/simendsjo/.cargo/registry/src/github.com-0a35038f75765ae4/pistoncore-glutin_window-0.4.0/src/lib.rs:61
   9:     0x7f1d28881c0c - GlutinWindow.From<WindowSettings>::from::h6dee4da3f2b294f2hga
                        at /home/simendsjo/.cargo/registry/src/github.com-0a35038f75765ae4/pistoncore-glutin_window-0.4.0/src/lib.rs:127
  10:     0x7f1d2880240c - convert::T.Into<U>::into::h17979526882165784022
                        at src/libcore/convert.rs:152
  11:     0x7f1d28801e1e - main::h0fd56d4a74d57dd1lTa
                        at src/main.rs:27
  12:     0x7f1d289df368 - rust_try_inner
  13:     0x7f1d289df355 - rust_try
  14:     0x7f1d289dc038 - rt::lang_start::h725b432f757180fdmbx
  15:     0x7f1d2880c65b - main
  16:     0x7f1d27d5378f - __libc_start_main
  17:     0x7f1d287ded48 - _start
  18:                0x0 - <unknown>
```

The offending `unwrap` seems to be in [line 61](https://github.com/PistonDevelopers/glutin_window/blob/master/src/lib.rs#L61).
I don't know any rust, so looking at the [`WindowBuilder`](https://github.com/tomaka/glutin/blob/master/src/window.rs#L170) in `glutin` doesn't give me any hints. Not sure if this is the right place to put this issue or if `glutin` or some other library would be the correct place.

I'm guessing I might be missing some system libraries, but I have no idea what.

```
$ pacaur -Ss freetype | grep installed
extra/freetype2 2.6-1 [installed]
extra/libxft 2.3.2-1 [installed]
multilib/lib32-freetype2 2.6-1 [installed]
multilib/lib32-libxft 2.3.2-1 [installed]

$ pacaur -Ss fontconfig | grep installed
extra/fontconfig 2.11.1-1 [installed]
multilib/lib32-fontconfig 2.11.1-1 [installed]
```

Any idea what I'm missing?

**Comment by tomaka** [comment]
I made some changes in glutin 0.3.2 that maybe fix this. Could you run `cargo update -p glutin` and see if it works?

**Comment by simendsjo** [comment]
Not sure how I should do this. The game doesn't reference `glutin` directly, so it's probably a dependency of `pistoncore-glutin_window`. Running the `update` command doesn't do anything.

**Comment by tomaka** [comment]
`cargo update` updates your Cargo.lock, then you do a regular `cargo build` or `cargo run`.

**Comment by simendsjo** [comment]
I updated the dependencies to the newest version, and got `glutin` too. It still fails, but with a different error:

```
$ RUST_BACKTRACE=1 cargo run                                                                                                        [±master ●●]
     Running `target/debug/rocket`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', src/libcore/result.rs:731
stack backtrace:
   1:     0x5624a273406e - sys::backtrace::write::h038220f50279f177vus
   2:     0x5624a2737435 - panicking::on_panic::h71219c6695575a6bpgx
   3:     0x5624a272f66e - rt::unwind::begin_unwind_inner::h82aba8beb356b6583Vw
   4:     0x5624a272fc2c - rt::unwind::begin_unwind_fmt::h39b470f67c9e92b29Uw
   5:     0x5624a2736e26 - rust_begin_unwind
   6:     0x5624a2769b04 - panicking::panic_fmt::hc9237b7ecab48700neC
   7:     0x5624a255ee31 - result::Result<T, E>::unwrap::h10796279148936200133
                        at src/libcore/macros.rs:28
   8:     0x5624a2559e5f - GlutinWindow::new::hc0e2395ee696eae1Kaa
                        at /home/simendsjo/.cargo/registry/src/github.com-0a35038f75765ae4/pistoncore-glutin_window-0.6.0/src/lib.rs:61
   9:     0x5624a25d08ac - GlutinWindow.From<WindowSettings>::from::h2215933d3c5ac812hga
                        at /home/simendsjo/.cargo/registry/src/github.com-0a35038f75765ae4/pistoncore-glutin_window-0.6.0/src/lib.rs:127
  10:     0x5624a254da9c - convert::T.Into<U>::into::h6131771467048164282
                        at src/libcore/convert.rs:152
  11:     0x5624a254d4ae - main::h4f7bc8279c6e781blTa
                        at src/main.rs:27
  12:     0x5624a273c298 - rust_try_inner
  13:     0x5624a273c285 - rust_try
  14:     0x5624a2738f68 - rt::lang_start::h725b432f757180fdmbx
  15:     0x5624a255972b - main
  16:     0x7f8d5ce4a78f - __libc_start_main
  17:     0x5624a252a3d8 - _start
  18:                0x0 - <unknown>
An unknown error occurred
```

**Comment by tomaka** [comment]
The problem most likely comes from [this line](https://github.com/aochagavia/rocket/blob/master/src/main.rs#L30):

``` rust
WindowSettings::new("Rocket", [1024, 600])
            .exit_on_esc(true)
            .opengl(opengl)
            .samples(8)   // <--
            .into();
```

Your system most likely doesn't support 8x MSAA. Since this is a purely cosmetic thing, you can simply remove this line.

Unfortunately none of the game, glutin or piston have a recovery system for when the requirements are not supported.

**Comment by simendsjo** [comment]
That fixed it. The error message is not very good though. If it would say "8 samples not supported by graphics card" or similar, it would have been easier to locate.

**Comment by tomaka** [comment]
Having a good error message is difficult because the algorithm is something like: (pseudo-code)

``` rust
for format in available_formats {
    if format.matches(&requirements) {
        return Ok(format);
    }
}
return Err(NotSupported);
```

**Comment by bvssvni** [comment]
@tomaka Perhaps use the requested requirements in the error message?
